spring.application.name=sb-ecom

spring.h2.console.enabled = true
#spring.datasource.url = jdbc:h2:mem:6967e831-f6db-4970-9dac-a6fc3f2a8c8f
spring.datasource.url=jdbc:h2:mem:test

#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql = true
#spring.jpa.hibernate.ddl-auto = update
